# The name of the workflow. GitHub displays the names of your workflows under your repository's "Actions" tab. If you omit `name`, GitHub displays the workflow file path relative to the root of the repository.
name: CI

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          artifact: test-results
          name: Workflow Report
          path: '*.xml'
          reporter: java-junit
          fail-on-error: true

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v1
#        if: success() || failure() # always run even if the previous step fails
#        with:
#          report_paths: '**/build/test-results/test/TEST-*.xml'
#      - name: Report
#        uses: dorny/test-reporter@v1
#        if: always()
#        with:
#          name: Maven Tests
#          path: target/surefire-reports/*.xml
#          reporter: java-junit
#          fail-on-error: true
